embodiment_id: cobotmagic_vla

simulation:
  class_type: CobotMagic
  uid: CobotMagic
  init_pos: [0.0, 0.0, 0.7775]
  init_qpos:
    - -0.3
    - 0.3
    - 1.0
    - 1.0
    - -1.2
    - -1.2
    - 0.0
    - 0.0
    - 0.6
    - 0.6
    - 0.0
    - 0.0
    - 0.05
    - 0.05
    - 0.05
    - 0.05

sensor:
  - sensor_type: Camera
    uid: cam_high
    width: 960
    height: 540
    intrinsics: [488.1665344238281, 488.1665344238281, 480, 270]
    extrinsics:
      eye: [0.35368482807598, 0.014695524383058989, 1.4517046071614774]
      target: [0.8586357573287919, 0, 0.5232553674540066]
      up: [0.9306678549330372, -0.0005600064212467153, 0.3658647703553347]

skill_profile:
  contract_id: single_arm_parallel_gripper
  profile_id: cobotmagic
  resources:
    - resource_id: primary_manipulator
      endpoints:
        - endpoint_id: motion
          control_part: right_arm
          capabilities:
            - kinematics.batch_inverse
            - motion.cartesian_pose
            - kinematics.forward
        - endpoint_id: grasp
          control_part: right_eef
          capabilities:
            - interaction.grasp
          command_preset: right_parallel_jaw_commands
  command_presets:
    - preset_id: right_parallel_jaw_commands
      control_part: right_eef
      commands:
        open: [0.05, 0.05]
        grasp: [0.0, 0.0]
